### ISSUE TITLE
Bouton DNS - Gérer les noms DNS des appareils

### ISSUE THREAD

**Issue by p-dor** [p-dor/LiveboxMonitor#10]
L'idée consiste à rajouter un bouton "DNS..." dans l'onglet principal (liste des appareils) permettant de visualiser les noms DNS assignés et de rajouter un bouton probablement dans l'onglet "Device Infos" pour assigner ou désassigner un nom DNS à un appareil.
Un nom DNS étant un nom comme un autre, peut être que simplement rajouter une option dans le bouton existant "Assign Name..." est suffisant.

**Comment by DrTableBasse** [comment]
honnêtement je vois pas comment tu peux rajouter une fonctionnalité bloquée par Orange eux même.

**Comment by BrN27** [comment]
Bonjour,

Je ne suis pas do tout expert, mais j'ai une petite question toute bête, est il possible d'ajouter une fonction permettant de modifier les DNS orange par défaut. Orange semble avoir verrouiller l'option mais je suppose malgré tout que quelque part, dans le code de la LiveBox, il doit s'y cacher une trace. Parce que changer ces DNS par appareil c'est pas très pratique.

**Comment by DrTableBasse** [comment]
non c'est pas possible

**Comment by p-dor** [comment]
Et je n'ai pas trouvé la moindre API pour le faire, elle est très bien cachée et quand bien même je la trouverai ça finirait en "access denied error" comme beaucoup d'autres...

**Comment by DrTableBasse** [comment]
et puis, après si c'est que le DNS qui pose problème, un petit routeur (ou avec un rasp) peut très bien faire l'affaire. Tu scinde ton réseau en deux parties : 
- un pour tout ce qui est télé etc...
- un pour ton / tes pc avec des besoins spécifiques et t'es tranquille

faut aussi comprendre la volonté d'empêcher des personnes de faire n'imp dans ton réseau. Même si bon, faut le faire surtout sur un réseau domestique mais bon


(je pense qu'on peut clôturer ici x) )

**Comment by p-dor** [comment]
Je vais garder le ticket ouvert car l'idée de départ n'était pas ça du tout ;-)
Je viens de changer le titre pour le rendre plus clair...

**Comment by DrTableBasse** [comment]
en soit juste un display des adresses DNS ou bien un message d'affichage donnant le DNS (btw on peut avoir ça avec ipconfig /all)

**Comment by p-dor** [comment]
Évolution correspondante poussée sur le repo : 
- Nouveau bouton "DNS..." dans l'onglet "Appareils" permettant d'avoir la liste des noms DNS assigné aux appareils.
- Possibilité d'assigner ou d'enlever un nom DNS à un appareil via le bouton "Assigner Nom..." de l'onglet Infos appareils.

Cette évolution fera partie de la release 1.2.

**Comment by p-dor** [comment]
Version 1.2 publiée avec l'amélioration, je ferme le ticket.
