### ISSUE TITLE
LB6 n'affiche pas les noms 

### ISSUE THREAD

**Issue by Adanorm** [p-dor/LiveboxMonitor#14]
Bonjour,

Je ne suis pas sur de moi, mais j'ai l'impression que la colonne Name devrait contenir une valeur.

![2023-01-26_193421](https://user-images.githubusercontent.com/46302945/214921127-bf2bd9e7-1281-4418-bc85-8488237dbee2.png)

**Comment by p-dor** [comment]
Bonsoir @Adanorm, c'est tout à fait normal mais je peux comprendre que cela rebute au début.
L'idée est de pouvoir identifier rapidement les appareils inconnus, justement en rouge comme cela. Mais au préalable il faut prendre la peine de nommer ceux qui sont connus, via l'onglet Device Info -> bouton "Assign Name...".
Au passage ce bouton permet de reprendre et/ou d'assigner le même nom que celui qu'on a donné à la Livebox.
Je vous conseille de lire un peu la documentation pour en savoir plus, j'y explique plus en détail pourquoi cela fonctionne comme cela.

**Comment by p-dor** [comment]
Documentation mise à jour (nouvelle section "Prise en main" pour clarifier cela).
