### ISSUE TITLE
Adaptation pour Livebox 4

### ISSUE THREAD

**Issue by p-dor** [p-dor/LiveboxMonitor#15]
Des utilisateurs rapportent que "cela fonctionne bien" avec une Livebox 4 mais comme aucune adaptation n'a réellement été faite il est à peu près certain que quelques fonctions ne doivent pas marcher comme elles le devraient.
Si des utilisateurs sont intéressés pour aider à faire ces adaptations en me communiquant quelques informations simples, merci de me contacter ici.

**Comment by JayRabas** [comment]
Hello
Je possède une livebox 4 et le seul truc bizarre que j'ai remarqué concerne les ports ethernet:
- Il n'y a pas d'infos concernant le port ethernet 1 (tableau à droite)
- Dans le tableau des débits (gauche), il semblerait qu'il y ait un décalage:
    - Ethernet 1 est le WAN ou Fiber
    - Ethernet 3 est Ethernet 2 (c'est le seul qui est connecté chez moi)

Si besoin je peux faire des tests
![Capture d’écran 2023-02-01 135835](https://user-images.githubusercontent.com/50320274/216049762-99706b0b-792b-4fe8-8b2c-2cd5fa566464.JPG)

**Comment by p-dor** [comment]
Bonsoir, merci pour votre aide. Effectivement il est certain que le mapping des interfaces soit différent entre la LB4 et la LB5.
Si vous savez utiliser sysbus ce qui m'aiderait beaucoup c'est d'avoir le résultat des appels :
`sysbus NeMo.Intf.lan:getMIBs`
et
`sysbus NeMo.Intf.guest:getMIBs mibs="wlanvap"`

Ce sera probablement trop gros pour être mis en réponse ici. Vous pouvez par exemple zipper les fichiers textes et poster un lien dessus via anonfiles ? Sinon par mail...

Merci !

**Comment by JayRabas** [comment]
Voilà le retour des 2 commandes:
[Livebox.zip](https://github.com/p-dor/LiveboxMonitor/files/10608852/Livebox.zip)

**Comment by p-dor** [comment]
Merci beaucoup, cela devrait me suffire, je vais regarder ça très prochainement.
Pour que le test du modèle dans le programme fonctionne bien est-ce que vous pourriez me confirmer que lorsque vous allez dans l'onglet "Livebox Stats/Infos", bouton "Livebox Infos", le champ "Model" affiche précisément "Livebox 4" ?

**Comment by JayRabas** [comment]
C'est bien "Livebox 4"!

**Comment by p-dor** [comment]
Bonsoir, j'ai commencé à regarder et hélas j'ai oublié de vous demander un autre résultat...
Pourriez vous aussi me donner le fichier retour pour la commande :
`sysbus NeMo.Intf.data:getMIBs`

Avec cela je devrai voir aussi le nom de l'interface fibre.
En fonction je risque de vous demander des retours sur les appels qui permettent d'avoir les détails d'une interface donnée, il s'agit de 
`sysbus NeMo.Intf.INTF:get`
en remplaçant INTF par le nom de l'interface. Mais pour l'instant il me faut tous les noms...

Merci encore pour votre aide !

**Comment by JayRabas** [comment]
Bonjour Pierre
Les 3 fichiers attachés
A+
[getIntfsTraverseAll.txt](https://github.com/p-dor/LiveboxMonitor/files/10716033/getIntfsTraverseAll.txt)
[getMIBs.txt](https://github.com/p-dor/LiveboxMonitor/files/10716034/getMIBs.txt)
[getMIBsTraverseAll.txt](https://github.com/p-dor/LiveboxMonitor/files/10716035/getMIBsTraverseAll.txt)

**Comment by p-dor** [comment]
Merci ! Alors maintenant tout s'explique, 'eth0' c'est bien l'interface WAN (donc fibre/ONT)...
J'ai aussi pu choper l'interface xDSL (bien indiquée comme désactivée chez vous), et je l'ai aussi rajoutée au cas où cela fonctionne pour les personnes en ADSL.

Je viens de pousser les adaptations, pouvez vous me dire si tout semble bien correspondre ?
Pour la ligne xDSL ça m'intéresse de savoir la liste affiche au moins des 0 pour les compteurs Down et Up ou rien du tout.
Pouvez vous aussi vérifier dans la liste principale (premier onglet) si dans la colonne "Link" ce sont bien les bons numéros de ports Ethernet qui sont affichés en fonction des appareils connectés ?

Merci.

**Comment by JayRabas** [comment]
Tout semble correct en ce qui concerne le filaire.
La ligne xDSL est vide, ce qui me parait cohérent vu qu'elle n'est pas utilisée.

Juste un truc que je ne comprends pas: même désactivé, le wifi affiche des données. Pas énormément mais il y a du débit de temps en temps.

**Comment by p-dor** [comment]
Très bien merci !
Pour en avoir le cœur net pourriez vous me dire ce que vous retourne ces 2 appels ?
`sysbus NeMo.Intf.dsl0:getNetDevStats`
`sysbus NeMo.Intf.dsl0:getDSLStats`
En toute logique, des erreurs...

Pour le léger traffic Wifi quand il est coupé je crois que j'ai ça aussi... et je ne peux pas l'expliquer non plus. Le programme se contente de capturer les compteurs d'octets renvoyés par la Livebox et d'afficher les différences, et si ces compteurs bougent c'est bien qu'il se passe quelque chose...

**Comment by JayRabas** [comment]
Hello
Pour la première commande:
erreur: {"result":{"status":null,"errors":[{"error":196618,"description":"Object or parameter not found","info":"getNetDevStats"}]}}

Pour la seconde:
{
    "status": {
        "ReceiveBlocks": 0,
        "TransmitBlocks": 0,
        "CellDelin": 0,
        "LinkRetrain": 0,
        "InitErrors": 0,
        "InitTimeouts": 0,
        "LossOfFraming": 0,
        "ErroredSecs": 0,
        "SeverelyErroredSecs": 0,
        "FECErrors": 0,
        "ATUCFECErrors": 0,
        "HECErrors": 0,
        "ATUCHECErrors": 0,
        "CRCErrors": 0,
        "ATUCCRCErrors": 0
    }
}

**Comment by p-dor** [comment]
Merci ! Ça veut dire qu'il me reste encore un petit truc à régler et ce sera tout bon pour les utilisateurs DSL aussi.

**Comment by p-dor** [comment]
Intégré dans la v1.0. Je ferme maintenant le ticket.

**Comment by p-dor** [comment]
Bonsoir @JayRabas, entre temps j'ai découvert une nouvelle API qui donne des informations précieuses sur les interfaces.
Il serait intéressant de l'essayer sur une LB4 pour voir si je n'ai rien oublié, si jamais vous avez deux minutes :
`sysbus HomeLan.Interface:get`

Merci d'avance pour votre aide !

**Comment by JayRabas** [comment]
Bonjour Pierre.
Le résultat de la commande: [HomeLan.Interface.get.txt](https://github.com/p-dor/LiveboxMonitor/files/10950983/HomeLan.Interface.get.txt)
