### ISSUE TITLE
[Linux] Colonnes trop petites

### ISSUE THREAD

**Issue by floviolleau** [p-dor/LiveboxMonitor#17]
Bonjour,

UN grand BRAVO pour ce super outil !

Il ne demande qu'à être amélioré avec le temps par la communauté

J'ai remarqué que sur certaines fenêtres, il n'est pas possible de redimensionner les colonnes. Je n'arrive donc pas à visualiser l'information (et il n'y a pas de tooltip) :
![image](https://user-images.githubusercontent.com/5442973/215818218-8bfb7c3c-107b-4529-b2e7-125672862ed5.png)

Merci !

**Comment by p-dor** [comment]
Bonjour @floviolleau, et merci pour ce retour.
Alors c'est normal, les colonnes qui ont un contenu de taille relativement fixe (comme les dates) ont une largeur statique. J'ai ajusté ça avec les fonts par défaut de Windows et forcément cela ne passe pas partout.
Cependant vous pouvez facilement résoudre cela en modifiant la taille de la font pour les lignes de listes dans les préférences (List Line Font Size). Par défaut sur Linux la valeur est à 10, vous pouvez essayer 9 pour voir si ça passe.
Je vois aussi sur votre copie d'écran que la taille des titres de colonne semble énorme, par défaut le paramètre List Header Font Size est à 12 sur Linux, vous avez laissé tel quel ?
Sinon pour la prochaine release je peux essayer d'élargir un peu ces colonnes statiques si vous me dites partout où cela dépasse...
Merci encore !

**Comment by floviolleau** [comment]
Bonjour,

Arf, c'est vrai j'avais vu l'option pour changer la taille de font.
Pour les tites de colonne, ça ne m'a pas choqué. J'ai laissé tel quel dans les préférences.

A voir si c'est possible facilement d'avoir un resize à la souris des colonnes pour éviter d'avoir à les fixer à une certaine taille ou de jouer avec les polices.

Sinon, ça fonctionne très bien sous linux avec un virtualenv et sur une livebox 4.
![image](https://user-images.githubusercontent.com/5442973/216561267-6ee76e91-1592-4a38-9d80-47d1b4aa6791.png)

Par contre, une flying 4G non (mais c'est logique 😃).

Entretemps, je suis passé à la fibre aérienne hier et je suis maintenant avec une Livebox 5 (hourra ça fait 3 ans qu'on l'attendait et que l'on se trainait à 1.2Mb/s !)

Valeurs paramètres avant modifications :
![image](https://user-images.githubusercontent.com/5442973/216560379-d4a65764-1769-475a-a0f5-38209d875674.png)

Après :
![image](https://user-images.githubusercontent.com/5442973/216561898-f169c647-3a32-4fec-a7a5-f8429e569327.png)

Résultat :
![image](https://user-images.githubusercontent.com/5442973/216561055-eddd7704-c0f6-4ec6-be0f-5a82062fe999.png)

Merci !

**Comment by p-dor** [comment]
Ok très bien ! Merci pour le retour.
Je vais voir pour les colonnes redimensionnables à la souris, je crois que ce n'est pas très compliqué.

**Comment by p-dor** [comment]
C'est bon toutes les colonnes sont maintenant ajustables à la souris, ce sera dans la prochaine release. Je vais pousser le code en même temps que l'implémentation de l'onglet DHCP, très bientôt.

**Comment by p-dor** [comment]
Le code avec les colonnes redimensionnables vient d'être poussé.
La release 1.0 ne va pas tarder.

**Comment by floviolleau** [comment]
Il y a des colonnes qui ne sont pas redimensionnables comme "name" et "Livebox name", "Link" sur la vue principale. Je n'ai pas fait le tour des autres vues.

Un oubli ?

**Comment by p-dor** [comment]
Alors en fait c'est normal mais probablement pas ultra intuitif. Il y a un mix de colonnes statiques (dont la taille ne bouge pas) et de colonnes dynamiques (dont la taille est dépendante de la taille de la fenêtre). Pour garder une bonne dynamicité des écrans j'ai laissé les colonnes dynamiques comme elles étaient, et seules les colonnes statiques sont redimensionnables. Hélas il n'y a pas de possibilité de rendre les colonnes dynamiques redimensionnables dans PyQT.
Donc si une colonne dynamique est trop petite il faut élargir un peu la fenêtre...
Si vous avec l'impression que ce n'est pas terrible je peux faire en sorte de ne garder qu'une et une seule colonne dynamique par liste pour rendre le maximum de colonne redimensionnables. Il en faut au moins une pour que les listes s'adaptent toujours à la largeur de la fenêtre.

**Comment by floviolleau** [comment]
Merci pour le retour. C'est plus clair et très bien comme ça.

Je ferme le ticket
