### ISSUE TITLE
Limiter la bande passante par appareil

### ISSUE THREAD

**Issue by Percy-Sky** [p-dor/LiveboxMonitor#19]
Bonjour ;
Cela fait maintenant depuis un moment que je cherche quelque chose capable de limité là bande passante de certains appareils directement depuis là Livebox et non l'appareil lui même.
Par exemple : Autoriser 64 mb/s à "PC2" et 936 mb/s à "PC1"

J'avais demandé la même chose sur un Forum qui m'a renvoyer sur cette application qui ne semble pas le faire ou j'ai mal compris comment sa fonctionne.

Désolé si cela n'a pas sa place ici dite le moi je supprime.
Merci

**Comment by p-dor** [comment]
Bonjour @Percy-Sky, hélas mes recherches ne m'ont pas permis d'identifier l'ombre d'un début de piste pour implémenter une telle chose avec la Livebox. Je pense que ce n'est tout simplement pas possible. Cependant des solutions commerciales de gestion de LAN (venant avec du hardware supplémentaire bien sûr), pourrait le faire mais j'imagine que vous voulez l'éviter.
La seule chose qui serait possible avec LiveboxMonitor serait d'alerter (via un trigger quelconque) quand la bandwidth dépasse une certaine limite pour un appareil donné.

**Comment by Percy-Sky** [comment]
Merci beaucoup pour t'a réponse je prend note de tes indications, c'est fou comment sur les forums fait pour sa tout le monde survol la question sans jamais répondre... alors qu'ici ce n'est pas fait pour sa et on me donne une réponse concrète, enfin bon Merci encore

**Comment by p-dor** [comment]
Bonjour, finalement mes recherches ont donné quelques résultats, que j'ai détaillé dans un nouveau ticket : https://github.com/p-dor/LiveboxMonitor/issues/34
Rien d'implémenté encore mais cela pourrait vous intéresser.
