### ISSUE TITLE
what do i put on user and password?

### ISSUE THREAD

**Issue by novakheey** [p-dor/LiveboxMonitor#20]
what do i put on user and password?when i open the .exe it tells me to put a user and a password what do i put here?and where do i find what do put?

**Comment by p-dor** [comment]
Hi,

You need to use exactly the same user/password that you use to log to the web application. The software doesn't use anything specific for this...

User must be 'admin' and the password is either what you set up yourself or if you didn't change it, it is what is in your Wifi card (corresponds to the first 8 characters, without spaces, of the security key visible on the sticker at the back of your Livebox).

Detailed information here in French:
https://assistance.orange.fr/livebox-modem/toutes-les-livebox-et-modems/installer-et-utiliser/piloter-et-parametrer-votre-materiel/l-interface-de-configuration/livebox-5-acceder-a-l-interface-de-configuration_292471-827404

Hope this helps.

**Comment by p-dor** [comment]
Documentation now up to date with those indications.
