### ISSUE TITLE
Conteneur docker

### ISSUE THREAD

**Issue by draco1544** [p-dor/LiveboxMonitor#21]
Bonjour ! J’aimerais en faire de ce logiciel un conteneur docker, le problème c’est que je pense qu’il manque une interface web, avez vous prévu de faire cela ?

**Comment by p-dor** [comment]
Bonjour, non l'esprit de départ de ce logiciel a été d'en faire un client lourd multi-plateformes, beaucoup plus simple à bien des égards y compris l'installation pour le commun des mortels.
Le repenser aujourd'hui en web UI obligerait à changer complètement l'approche du code, faire un serveur avec des APIs REST, etc... Ce serait un énorme travail que mon maigre temps ne me permettrait pas.
Par contre tout le code est ouvert et si quelqu'un veut tenter l'aventure je peux essayer de donner un minimum de support dans cette initiative qui devrait devenir un fork de ce projet.
