### ISSUE TITLE
Compteurs de trafic limités à 4 Go

### ISSUE THREAD

**Issue by draco1544** [p-dor/LiveboxMonitor#22]
Lorsque j'accède à la page pour voir les infos d'upload et de download totale de la fibre de la box je remarque que le compteur se réinitialise dès qu'il dépasse le 4Go environ. Est-ce normal ?

**Comment by p-dor** [comment]
Bonsoir @draco1544, oui c'est tout à fait normal et indépendant du programme en fait.
La Livebox comptabilise le trafic sur des entiers de 32 bits, avec une granularité à l'octet près. Si vous faites le calcul vous verrez que sur 32 bits on ne peut pas dépasser les 4 Go, ce qui fait que le compteur repasse à zéro une fois cette limite atteinte.
Par contre votre remarque me fait penser que la documentation devrait être plus claire là dessus, je vais mettre quelque chose dans ce sens.

**Comment by draco1544** [comment]
> Bonsoir @draco1544, oui c'est tout à fait normal et indépendant du programme en fait.
> 
> La Livebox comptabilise le trafic sur des entiers de 32 bits, avec une granularité à l'octet près. Si vous faites le calcul vous verrez que sur 32 bits on ne peut pas dépasser les 4 Go, ce qui fait que le compteur repasse à zéro une fois cette limite atteinte.
> 
> Par contre votre remarque me fait penser que la documentation devrait être plus claire là dessus, je vais mettre quelque chose dans ce sens.

C'est vraiment dommage car je souhaitais utiliser le logiciel pour enregistrer la quantité de bande passante utiliser sur plusieurs mois

**Comment by p-dor** [comment]
Alors votre demande rejoint celle ci : [Net Graph & export CVS](https://github.com/p-dor/LiveboxMonitor/issues/5)
Aujourd'hui le logiciel se borne à simplement afficher ce compteur en temps réel et en déduire une utilisation de la bande passante par seconde, il ne stocke rien et la seule persistence reste ce simple compteur dans la Livebox.
Un export CVS (lui aussi en temps réel) couplé à une gestion intelligente de la remise à zéro du compteur vous permettrai de compiler des stats sur une longue durée de manière viable.

**Comment by p-dor** [comment]
Bonne nouvelle, je viens de trouver de nouvelles APIs (bien cachées !) qui offrent des compteurs sur 64bits pour toutes les interfaces, donc déjà les compteurs vont arrêter de se recycler au bout de 4 Go dans la prochaine version. Et donc on pourra voir l'évolution sur une longue plage de temps, sans avoir forcément le logiciel qui tourne puisque les compteurs sont maintenus par la Livebox...

Pour les curieux :
- `HomeLan.Interface:get` est magique pour retrouver toutes les interfaces, avec leur nom interne et leur nom affichable. Si j'avais eu ça avant, ça m'aurait fait gagner un temps fou...
- `HomeLan.Interface.INTF.Stats:get` pour retrouver les stats, en remplaçant INTF par le nom interne de n'importe quelle interface.

**Comment by draco1544** [comment]
> Bonne nouvelle, je viens de trouver de nouvelles APIs (bien cachées !) qui offrent des compteurs sur 64bits pour toutes les interfaces, donc déjà les compteurs vont arrêter de se recycler au bout de 4 Go dans la prochaine version. Et donc on pourra voir l'évolution sur une longue plage de temps, sans avoir forcément le logiciel qui tourne puisque les compteurs sont maintenus par la Livebox...
> 
> 
> 
> Pour les curieux :
> 
> - `HomeLan.Interface:get` est magique pour retrouver toutes les interfaces, avec leur nom interne et leur nom affichable. Si j'avais eu ça avant, ça m'aurait fait gagner un temps fou...
> 
> - `HomeLan.Interface.INTF.Stats:get` pour retrouver les stats, en remplaçant INTF par le nom interne de n'importe quelle interface.
> 
> 
> 
> EDIT : bon après avoir essayé "en vrai" c'est très nettement moins bien que les interfaces que j'utilise depuis le début... Les statistiques ne se rafraichissent pas en temps réel sauf pour le WAN et la Fibre, et encore... et puis les compteurs se recyclent aussi quand ils veulent, ça repasse à zéro parfois après 512 Go, parfois à 3 Go, ... ce n'est pas fiable hélas. Je vais donc devoir laisser comme c'était.

C'est vraiment vraiment dommage

**Comment by p-dor** [comment]
Je ferme ce ticket car aucune solution ne semble se profiler autre que faire cette vue NetGraph / Export CVS (prochainement).
Comme un ticket est déjà dédié pour ces fonctionnalités...

**Comment by p-dor** [comment]
Bonjour, en attendant l'implémentation de la vue graphique (je suis dessus en ce moment) je viens de pousser sur le repo une amélioration qui affiche des compteurs qui ne se recyclent plus à 4 Go pour la plupart des interfaces mais pas toutes. Comme il s'agit de l'interprétation d'événements arrivant toutes les 30 secondes environ, les compteurs de base s'affichent au départ, mais dès que les événements avec les compteurs de plus haute résolution arrivent ils sont remplacés par ceux-ci...
Si vous voulez tester en attendant la release qui arrivera bientôt.

**Comment by p-dor** [comment]
La release v1.1 contenant cette évolution + les graphes & export CSV des statistiques est maintenant publiée.
