### ISSUE TITLE
Error loading Python lib '/var/folders/q2/y3cflmhj5cx9lxfq56p064s00000gn/T/_MEIIpyaQ1/Python

### ISSUE THREAD

**Issue by eravion** [p-dor/LiveboxMonitor#23]
Bonjour,

Je suis sur Macos Mojave 10.14.6.

J'ai ce message d'erreur lorsque je lance LiveboxMonitor depuis un terminal (en cliquant sur l'icone, il ne se lance pas)

[55533] Error loading Python lib '/var/folders/q2/y3cflmhj5cx9lxfq56p064s00000gn/T/_MEIIpyaQ1/Python': dlopen: dlopen(/var/folders/q2/y3cflmhj5cx9lxfq56p064s00000gn/T/_MEIIpyaQ1/Python, 10): no suitable image found.  Did find:
	/var/folders/q2/y3cflmhj5cx9lxfq56p064s00000gn/T/_MEIIpyaQ1/Python: cannot load 'Python' (load command 0x80000034 is unknown)
	/private/var/folders/q2/y3cflmhj5cx9lxfq56p064s00000gn/T/_MEIIpyaQ1/Python: cannot load 'Python' (load command 0x80000034 is unknown)

**Comment by eravion** [comment]
En complément, l'installation à la main passe avec python3.9.
Le pb doit être dans le binaire fournit ?

**Comment by p-dor** [comment]
Bonjour, avez vous pris la bonne version entre Intel / Silicon en fonction de votre processeur ? Si vous êtes sur Silicon avez vous essayé la version Intel en émulation ?
Sinon j'ai bien peur que ce problème soit dépendant de votre configuration... Une recherche _MacOS "(load command 0x80000034 is unknown)"_ sur Google retourne beaucoup de références avec des problèmes similaires avec Python.

**Comment by p-dor** [comment]
Je ferme ce ticket n'ayant aucune réponse.

**Comment by amrx06** [comment]
Bonjour,
j'ai le même problème.
MacOS 10.13.6 (une antiquité), MacIntel avec la bonne version chargée. 
Python 3.9.13 installé
`/Applications/LiveboxMonitor.app/Contents/MacOS/LiveboxMonitor
[64405] Error loading Python lib '/var/folders/29/1j8857vj4g56n88k9pfgwyy80000gn/T/_MEI7rTByJ/Python': dlopen: dlopen(/var/folders/29/1j8857vj4g56n88k9pfgwyy80000gn/T/_MEI7rTByJ/Python, 10): no suitable image found.  Did find:
	/var/folders/29/1j8857vj4g56n88k9pfgwyy80000gn/T/_MEI7rTByJ/Python: cannot load 'Python' (load command 0x80000034 is unknown)
	/var/folders/29/1j8857vj4g56n88k9pfgwyy80000gn/T/_MEI7rTByJ/Python: stat() failed with errno=3`

**Comment by p-dor** [comment]
Bonsoir @amrx06, et un lancement via les sources directement avec Python 3.9.13 fonctionne correctement ?
Cela fait trois personnes maintenant qui remontent ce problème sur des anciens Mac, cela provient probablement de PyInstaller... je vais investiguer un peu plus.

**Comment by amrx06** [comment]
l'installation de PyQt6 a échoué. je n'ai pas pu tester avec le code source.

**Comment by p-dor** [comment]
Bonjour, après une petite recherche il est déjà clair que l'application en téléchargement construite avec PyInstaller ne peut pas fonctionner sur une version de MacOS inférieure à la 10.15 (Catalina) :
https://pyinstaller.org/en/stable/requirements.html

Pour PyQt6 je cherche encore, difficile de trouver une source fiable.

Quand tout sera clair je mettrai une section sur la configuration système minimum dans la documentation.

**Comment by p-dor** [comment]
Résultat des courses, c'est la même dépendance pour PyQt6 :
https://www.qt.io/product/qt6/technical-specifications

Avec ou sans PyInstaller cela veut dire que le programme ne peut pas fonctionner sur des versions antérieures à Catalina (10.15).
Je vais m'atteler à mettre ces dépendances clairement dans la documentation.
