### ISSUE TITLE
statistiques: valeur vide pendant l'actualisation des données  

### ISSUE THREAD

**Issue by Raiiyzen** [p-dor/LiveboxMonitor#24]
Bonjour, 

Tout d'abord merci pour ton soft qui reste très pratique de par le manque d'informations dont on dispose via l'interface web d'Orange. 

j'ai remarqué que quand je suis dans l'onglet "Livebox Stats/Infos", les statistiques en direct deviennent tout d'un coup nulle (plus rien ne s'affiche), puis ca revient quelques secondes plus tard, je suppose peut être qu'il s'agit du temps entre l'actualisation pour récupérer la dernière valeur la plus récente.  Serait-il possible de laisser affiché la dernière valeur récupérée, plutôt que de ne rien afficher si la dernière actualisation n'a pas aboutie ? 

Raiiyzen

**Comment by p-dor** [comment]
Bonjour, comme l'indique la documentation ces valeurs sont rafraichies toutes les secondes. S'il ne se passe rien (les compteurs n'ont pas bougé) la case devient vide (plutôt qu'afficher 0). Le but c'est de mieux voir quand il se passe quelque chose plutôt que rien.
Si on laisse l'ancienne valeur la seconde d'après alors qu'il ne se passe rien donnera une fausse information.
Ce que vous recherchez ressemble plus à d'autres demandes de type NetGraph ou exports CVS qui permettent de voir l'évolution dans le temps.

**Comment by p-dor** [comment]
Doublon avec l'export CVS (ou un futur NetGraph...).

**Comment by p-dor** [comment]
Bonsoir je réouvre ce ticket car je viens d'essayer de changer la fréquence de rafraichissement des statistiques de 1 seconde à 3 secondes et effectivement c'est très nettement plus confortable à lire (les valeurs sont visibles plus longtemps).
Je vais donc mettre cette fréquence en paramètre, avec 3 secondes par défaut, et chacun mettra ce qu'il veut...
Je garde le ticket tant que la release n'aura pas été poussée avec ce changement.

**Comment by p-dor** [comment]
La fréquence de rafraîchissement est maintenant réglables dans les paramètres et mise à 3 secondes par défaut.

**Comment by p-dor** [comment]
Intégré dans la v1.0. Je ferme maintenant le ticket.
