### ISSUE TITLE
Plantage et problème de connexion si logs activées dans la version sans console

### ISSUE THREAD

**Issue by cbouju** [p-dor/LiveboxMonitor#28]
Depuis ce matin, lors de son lancement LiveboxMonitor 1.00 ne peut plus se connecter sur ma Livebox 5, alors qu'il fonctionnait jusqu'à présent.

J'ai essayé chacun de ces différents moyens pour résoudre le problème :
- aucune des adresses de connexion ne fonctionne y compris 192.168.1.1
- vérification du pare-feu de mon PC sous Windows 10, ainsi que celui de la box
- téléchargement sur ce site d'une nouvelle version de LM 1.00
- suppression de tous les fichiers de configuration dans %APPDATA%\LiveboxMonitor

Aucun de ces essais n'est fructueux.

Cependant LiveboxMonitor 0.97 fonctionne, aussi je me demande ce qui a changé entre les 2 versions, et qui pourrait être à l'origine de mon problème.

**Comment by p-dor** [comment]
Bonsoir, la seule chose qui a changé c'est d'avoir mis le nom du profil courant dans le nom du fichier qui stocke le cookie de connexion.
Ces cookies sont stockés dans le répertoire %temp%, avec comme format LiveboxMonitor_NomDuProfil_state.
Comme vous n'utilisez probablement qu'un seul profil avec le nom par défaut "Main" ça doit donner un fichier LiveboxMonitor_Main_state.

Mais ce qui est étrange c'est que si la connexion échoue avec le cookie le programme essai de réinitier une connexion sans...
Sauf si le fichier cookie est corrompu, dans ce cas le programme va planter car son décodage n'est pas protégé des exceptions.

Essayez peut être en supprimant tous les cookies que vous pouvez voir dans le répertoire %temp% et utilisez une version "Console" du programme pour voir s'il affiche une erreur particulière dans la console qui pourrait aider...
Essayez aussi de mettre le niveau de log à 2 dans la configuration, les messages seront peut être plus parlant.

Tenez moi au courant, cela cache peut être un bug effectivement.

**Comment by cbouju** [comment]
Bonsoir, le problème est réglé.

J'avais 2 fichiers cookies dans le dossier %temp% :
- un fichier LiveboxMonitor_Main_state vide (0 octets),
- et un autre LiveboxMonitor_state (139 octets, celui de la version 0.97 ?)
J'ai effacé ces 2 fichiers, et le programme refonctionne parfaitement.

De mémoire, j'avais fermé le programme à un moment où la Livebox mettait un temps trop long à répondre, ce qui explique peut-être le fichier cookie vide.

Merci pour votre aide, et pour ce superbe programme ! 👍

**Comment by p-dor** [comment]
Bonsoir, je soupçonne un problème d'accès en écriture sur votre dossier %temp% mais rien n'est sûr.
Il n'est pas normal du tout par exemple que le premier fichier ait été vide.
Et je confirme que le second était celui de la version 0.9.7. D'ailleurs il serait intéressant de recommencer un test avec la version 0.9.7 maintenant que le cookie n'est plus là (cela ne devrait plus fonctionner).
Il faudrait m'en dire plus, qu'est ce qui se passe exactement quand cela ne fonctionne pas ? Le programme quitte inopinément ? Il affiche quelque chose ?
Pourriez vous essayer avec la version _Console comme suggéré ? La console affichera forcément quelque chose...

**Comment by cbouju** [comment]
Bonsoir, je crois avoir trouvé l'origine du problème, il se produit après avoir mis le niveau de log à 1 ou 2 dans la version 1.00 sans console.

Dans ce cas cette version plante au bout de quelques secondes, puis lorsque je la relance elle affiche la fenêtre suivante :
Titre : Connexion Livebox [Main]
Impossible de se connecter à la Livebox
Peut-être temporaire, etc ....

Pour "réparer" le problème, il faut effectivement lancer la version 1.00 avec console, puis remettre le niveau de log à 0 avant de relancer la version 1.00 sans console.

A noter que la version 0.97 n'a pas ce problème (de plantage de la version sans console après avoir changé le niveau de log.

Enfin pour répondre à toutes vos questions, après avoir supprimé les fichiers cookies, le lancement de chacune de ces 2 versions en recrée un nouveau sans provoquer de problème particulier.

Merci pour votre attention, et pour ce superbe programme qui pallie très bien le niveau déplorable de celui de la Livebox.

**Comment by p-dor** [comment]
Rebonsoir, bravo pour vos tests et effectivement j'ai pu le reproduire chez moi.
La version sans console plante si les logs sont activées... Et je confirme que chez moi la version 0.9.7 n'a pas ce comportement.
Je vais investiguer ça pour fixer ce problème dans la prochaine version.
Merci pour votre aide.

**Comment by p-dor** [comment]
Et j'ai trouvé le coupable... c'est PyInstaller.
En effet je l'ai mis à jour entre la version 0.9.7 et la 1.0, et plusieurs personnes rapporte un problème similaire avec les logs...
Par exemple :
https://www.mail-archive.com/pyinstaller@googlegroups.com/msg09004.html

**Comment by cbouju** [comment]
👍 👍 👍

**Comment by p-dor** [comment]
Le fix est maintenant dispo dans le repo, il fera parti de la prochaine release.

**Comment by p-dor** [comment]
La release v1.1 contenant la correction est maintenant publiée.

**Comment by cbouju** [comment]
👍
