### ISSUE TITLE
Connexion impossible à la livebox 6

### ISSUE THREAD

**Issue by Asushen** [p-dor/LiveboxMonitor#3]
Message d'erreur " cannot connect to the Livebox." avec Livebox 6
![Capture d'écran_20230109_202024](https://user-images.githubusercontent.com/96844588/211390345-59fef1cd-0591-4441-a577-70ea48271f63.png)

solution trouvée: modifier l'URL dans le fichier User/appdata/roaming/LiveboxMonitor/config.txt 
remplacer "Livebox URL": "http://livebox.home/",  par  "Livebox URL": "http://livebox/",

**Comment by p-dor** [comment]
Bonsoir, effectivement la solution dans ce genre de cas est de bien paramétrer l'URL dans le fichier de configuration, et tout dépend du DNS utilisé pour accéder à la Livebox.
J'avais mis "http://livebox.home/" car c'est la bonne URL pour la Livebox 4 (le programme fonctionne aussi assez largement pour ce modèle) et apparemment cela fonctionnait correctement jusque là aussi pour Livebox 5 et 6, mais je pense que vous avez raison :  "http://livebox/" tout court est bien l'URL correcte pour ces deux modèles. Comme le programme cible ces modèles principalement, je vais mettre à jour la configuration par défaut pour mettre cette URL là. Merci pour l'avoir signalé.

**Comment by p-dor** [comment]
Bonsoir @Asushen, après réflexion et d'autres utilisateurs qui me reportent être dans le cas inverse (livebox.home qui fonctionne mais pas livebox tout court, y compris sur Livebox 6) je m'interroge de nouveau sur la bonne URL à mettre par défaut.
Ce n'est pas bien grave car on peut facilement mettre l'URL qui fonctionne dans le fichier de configuration comme vous l'avez fait, mais tout porte à croire que livebox.home devrait fonctionner partout. Avez vous une configuration un peu spéciale ? Par exemple avez vous désactivé le serveur DHCP de la Livebox ou modifié son adresse IP ?
Que donne chez vous les commandes 
```
nslookup livebox.home
nslookup livebox
```
sur un terminal ?
Merci pour votre aide.

**Comment by Asushen** [comment]
> Bonsoir @Asushen, après réflexion et d'autres utilisateurs qui me reportent être dans le cas inverse (livebox.home qui fonctionne mais pas livebox tout court, y compris sur Livebox 6) je m'interroge de nouveau sur la bonne URL à mettre par défaut. Ce n'est pas bien grave car on peut facilement mettre l'URL qui fonctionne dans le fichier de configuration comme vous l'avez fait, mais tout porte à croire que livebox.home devrait fonctionner partout. Avez vous une configuration un peu spéciale ? Par exemple avez vous désactivé le serveur DHCP de la Livebox ou modifié son adresse IP ? Que donne chez vous les commandes
> 
> ```
> nslookup livebox.home
> nslookup livebox
> ```
> 
> sur un terminal ? Merci pour votre aide.

Bonjour,
entre temps j'ai changé de carte mère et réinstallé Windows donc je ne connait pas exactement les paramètres réseaux utilisés. Mais j'avais changé les DNS pour ceux d'un pihole qui tourne sur mon LAN .Du coup je ne comprends pas pourquoi ça fonctionnait en mettant juste " livebox"
j'ai configuré le pihole pour utiliser la livebox comme serveur DNS et maintenant tout fonctionne

C:\Users\****>nslookup livebox.home
Serveur :   pi.hole
Address:  2a01:cb04:****
Nom :    livebox.home
Addresses:  2a01:cb04:*****
          192.168.1.1

C:\Users\****>nslookup livebox
Serveur :   pi.hole
Address:  2a01:cb04:*****
Nom :    livebox.home
Addresses:  2a01:cb04:*****
          192.168.1.1
