### ISSUE TITLE
Livebox 4 - ONT Infos - Erreur de query

### ISSUE THREAD

**Issue by An78toi13ne06** [p-dor/LiveboxMonitor#30]
Bonjour,

Lorsque j'essaie d'obtenir les informations de l'ONT connecté à ma Livebox 4 j'obtiens le message d'erreur suivant : 
![image](https://user-images.githubusercontent.com/17361604/223263945-b125abb3-f20b-452c-8810-52b7f9e1c4fa.png)

Je suis sous macOS Ventura 13.2.

Cordialement.

**Comment by An78toi13ne06** [comment]
Petite correction venant de me rendre compte que je n'avais pas la dernière version : Je n'ai juste pas d'infos qui s'affiche.
![Capture d’écran 2023-03-06 à 23 52 37](https://user-images.githubusercontent.com/17361604/223274874-59183eb3-c708-4fd7-a58b-7e89a0ea481f.png)

**Comment by p-dor** [comment]
Bonsoir, alors c'est normal : la version 0.9.7 n'était pas vraiment adaptée pour la LB4, d'où l'erreur.
La v1.0 dispose d'un mapping des interfaces corrects pour la LB4 (les stats doivent s'afficher correctement), cependant aucune interface évidente ne permet d'obtenir les informations ONT comme on peut les avoir avec les LB5 ou 6. Du coup aucune information ne s'affiche...
Ne disposant que d'une LB5 c'est un peu compliqué pour faire plus de recherches mais si vous avez Python installé ainsi que le package sysbus, vous pouvez probablement m'aider un peu... Dites moi.
Évidement le seul espoir d'arriver à trouver une API qui fonctionne c'est uniquement si vous avez l'ONT intégré dans la Livebox et pas un module externe. Mais même avec l'ONT intégré ce n'est pas gagné du tout d'avance...

**Comment by An78toi13ne06** [comment]
Bonsoir,
Je n'avais pas le package sysbus mais je l'ai installé et vérifié son fonctionnement.
Si vous avez des besoin avec sysbus, n'hésitez pas à m'en faire part.

**Comment by p-dor** [comment]
Bonsoir @An78toi13ne06, bonne nouvelle merci ! En effet il serait intéressant de m'envoyer ce que vous retourne cette ligne :
`sysbus HomeLan.Interface:get`

Merci pour votre aide.

**Comment by An78toi13ne06** [comment]
La commande renvoie le résultat suivant :
`{
    "status": {
        "wl0": {
            "FriendlyName": "2.4GHz-Private_SSID",
            "Name": "wl0",
            "Alias": "WiFi",
            "NumberOfStoredMeasures": 0
        },
        "eth6": {
            "FriendlyName": "5GHz-Private_SSID",
            "Name": "eth6",
            "Alias": "WiFi",
            "NumberOfStoredMeasures": 0
        },
        "wlguest2": {
            "FriendlyName": "2.4GHz-Guest_SSID",
            "Name": "wlguest2",
            "Alias": "WiFi",
            "NumberOfStoredMeasures": 0
        },
        "wlguest5": {
            "FriendlyName": "5GHz-Guest_SSID",
            "Name": "wlguest5",
            "Alias": "WiFi",
            "NumberOfStoredMeasures": 0
        },
        "eth1": {
            "FriendlyName": "eth1",
            "Name": "eth1",
            "Alias": "Eth",
            "NumberOfStoredMeasures": 0
        },
        "eth2": {
            "FriendlyName": "eth2",
            "Name": "eth2",
            "Alias": "Eth",
            "NumberOfStoredMeasures": 0
        },
        "eth3": {
            "FriendlyName": "eth3",
            "Name": "eth3",
            "Alias": "Eth",
            "NumberOfStoredMeasures": 8680
        },
        "eth4": {
            "FriendlyName": "eth4",
            "Name": "eth4",
            "Alias": "Eth",
            "NumberOfStoredMeasures": 8680
        },
        "dsl0": {
            "FriendlyName": "xDSL",
            "Name": "dsl0",
            "Alias": "",
            "NumberOfStoredMeasures": 0
        },
        "dsl0_sync": {
            "FriendlyName": "xDSL-Sync",
            "Name": "dsl0",
            "Alias": "",
            "NumberOfStoredMeasures": 0
        },
        "atm_data": {
            "FriendlyName": "ADSL-Internet",
            "Name": "atm_data",
            "Alias": "xDSL_Virtual",
            "NumberOfStoredMeasures": 0
        },
        "atm_multi": {
            "FriendlyName": "ADSL-MultiServices",
            "Name": "atm_multi",
            "Alias": "xDSL_Virtual",
            "NumberOfStoredMeasures": 0
        },
        "atm_voip": {
            "FriendlyName": "ADSL-VoIP",
            "Name": "atm_voip",
            "Alias": "xDSL_Virtual",
            "NumberOfStoredMeasures": 0
        },
        "atm_iptv1": {
            "FriendlyName": "ADSL-IPTV_VOD",
            "Name": "atm_iptv1",
            "Alias": "xDSL_Virtual",
            "NumberOfStoredMeasures": 0
        },
        "atm_iptv2": {
            "FriendlyName": "ADSL-IPTV_Zapping",
            "Name": "atm_iptv2",
            "Alias": "xDSL_Virtual",
            "NumberOfStoredMeasures": 0
        },
        "atm_iptv3": {
            "FriendlyName": "ADSL-IPTV_Live1",
            "Name": "atm_iptv3",
            "Alias": "xDSL_Virtual",
            "NumberOfStoredMeasures": 0
        },
        "atm_iptv4": {
            "FriendlyName": "ADSL-IPTV_Live2",
            "Name": "atm_iptv4",
            "Alias": "xDSL_Virtual",
            "NumberOfStoredMeasures": 0
        },
        "vvlan_data": {
            "FriendlyName": "VDSL-Internet",
            "Name": "vvlan_data",
            "Alias": "xDSL_Virtual",
            "NumberOfStoredMeasures": 0
        },
        "vvlan_multi": {
            "FriendlyName": "VDSL-MultiServices",
            "Name": "vvlan_multi",
            "Alias": "xDSL_Virtual",
            "NumberOfStoredMeasures": 0
        },
        "vvlan_voip": {
            "FriendlyName": "VDSL-VoIP",
            "Name": "vvlan_voip",
            "Alias": "xDSL_Virtual",
            "NumberOfStoredMeasures": 0
        },
        "vvlan_iptv1": {
            "FriendlyName": "VDSL-IPTV",
            "Name": "vvlan_iptv1",
            "Alias": "xDSL_Virtual",
            "NumberOfStoredMeasures": 0
        },
        "eth0": {
            "FriendlyName": "WAN_Ethernet",
            "Name": "eth0",
            "Alias": "",
            "NumberOfStoredMeasures": 8680
        },
        "vlan_data": {
            "FriendlyName": "WAN_Ethernet-Internet",
            "Name": "vlan_data",
            "Alias": "WAN_Virtual",
            "NumberOfStoredMeasures": 0
        },
        "vlan_multi": {
            "FriendlyName": "WAN_Ethernet-MultiServices",
            "Name": "vlan_multi",
            "Alias": "WAN_Virtual",
            "NumberOfStoredMeasures": 8680
        },
        "vlan_voip": {
            "FriendlyName": "WAN_Ethernet-VoIP",
            "Name": "vlan_voip",
            "Alias": "WAN_Virtual",
            "NumberOfStoredMeasures": 0
        },
        "vlan_iptv1": {
            "FriendlyName": "WAN_Ethernet-IPTV_VOD",
            "Name": "vlan_iptv1",
            "Alias": "WAN_Virtual",
            "NumberOfStoredMeasures": 0
        },
        "vlan_iptv2": {
            "FriendlyName": "WAN_Ethernet-IPTV_Live",
            "Name": "vlan_iptv2",
            "Alias": "WAN_Virtual",
            "NumberOfStoredMeasures": 8680
        }
    }
}`

**Comment by p-dor** [comment]
Bonjour et merci.
Cela confirme deux choses :
- Les réglages actuels du programme sont corrects pour la LB4.
- Aucune interface n'est référencée pour l'ONT... À part afficher une erreur plus claire (ou griser le bouton) je ne vais pas pouvoir faire grand chose hélas.

**Comment by p-dor** [comment]
En conséquence le programme n'affiche plus le bouton ONT pour les LB4, c'est plus radical.

**Comment by p-dor** [comment]
La release v1.1 contenant cette évolution est maintenant publiée.
