### ISSUE TITLE
Ne se lance/installe même pas

### ISSUE THREAD

**Issue by Kobalt77** [p-dor/LiveboxMonitor#31]
Bonjour!

Je ne suis peut etre pas le premier (enfin j'espère) mais, quand je lance le LiveboxMonitor.exe, j'obtiens 2 fenetres d'erreur puis plus rien

![LiveboxMonitor_2023-03-07_15-16-10](https://user-images.githubusercontent.com/38300027/223448671-1804dd60-bfa7-4068-a2e2-7260efb21661.jpg)
![LiveboxMonitor_2023-03-07_15-16-19](https://user-images.githubusercontent.com/38300027/223448673-46d5bc78-d38f-42c7-b297-fc314734ba42.jpg)

Est-ce normal?
Je suis sous Win7 64bits

**Comment by p-dor** [comment]
Bonsoir cela ressemble un peu à ces problèmes remontés sur Mac :
https://github.com/p-dor/LiveboxMonitor/issues/23

Il semblerait que PyInstaller supporte mal les systèmes trop anciens, et peut être même que PyQT6 (la librairie utilisée pour l'interface graphique) aussi. C'est vrai que tourner sur Win7 en 2023 il faut oser ;-)

Mais je vais investiguer un peu ce week-end, tout espoir n'est pas encore perdu...

**Comment by Kobalt77** [comment]
Jamais eu l'occasion de changer pour Win10 ou autre et pas le matos assez puissant pour les faire tourner de toute manière 😅

**Comment by p-dor** [comment]
Bonjour, après une recherche rapide les espoirs sont je pense définitivement perdus pour Win7...
https://groups.google.com/g/pyinstaller/c/XcTSSsPP5ac

-> PyInstaller ne supporte pas Win7.
-> Et Python 3.9 ne tourne pas sur Win7 de toute façon...

Je pense que c'est mort désolé.
Je ferme le ticket mais je change le titre pour la postérité.

**Comment by josephernest** [comment]
Je viens de tester, et `lbm.py` a l'air de démarrer sous Python 3.8 (j'ai pas l'impression que vous utilisez des fonctions spécifiques Python 3.9, est-ce le cas @p-dor?).

Par contre `PyQt6` ne marche pas sous Windows 7, j'ai essayé de remplacer toutes les instances de `PyQt6` par `PyQt5`, ça démarre mais ça s'arrête là:

![image](https://github.com/user-attachments/assets/25f73327-59db-428c-a4cb-d76816dd3d78)

LBM utilise-t-il des choses spécifiques à PyQt6 et qui ne marchent pas sous PyQt5?

**Comment by p-dor** [comment]
Oui PyQt6 est nécessaire et son utilisation est incompatible avec PyQt5.
