### ISSUE TITLE
Onglet NAT/PAT

### ISSUE THREAD

**Issue by p-dor** [p-dor/LiveboxMonitor#32]
Créer un nouvel onglet pour paramétrer les règles NAT/PAT directement depuis l'application, dans le même esprit que l'onglet DHCP.
Un export/import des règles sera bienvenu.

**Comment by colombani** [comment]
Cela serait en effet très utile

**Comment by aldoushx** [comment]
Oui je confirme, très utile puisque l'interface d'admin de la livebox est buggée sur cet onglet précisément et ne permet plus de gérer les règles de forwarding pour un grand nombre de personnes !

**Comment by p-dor** [comment]
Prochaine priorité du projet.

**Comment by p-dor** [comment]
Le support du nouvel onglet NAT/PAT vient d'être poussé sur le repo. De façon inattendue il s'agit par ailleurs du plus gros module du logiciel en terme de taille de code... 🥇 
Quelques retours de tests seront bienvenus avant que je génère prochainement la release 1.2.

**Comment by aldoushx** [comment]
Je suis en train de tester : quand je clique sur l'onglet NAT/PAT j'obtiens une erreur : Cannot load IPv4 port forwarding rules.
Peut-être la cause est-elle la même que celle qui fait bugger la page de l'interface web d'aministration ?
Je précise que cette page ne s'affiche plus chez moi depuis longtemps.

**Comment by p-dor** [comment]
Oui c'est très probable car cela veut dire que le problème vient de la Livebox elle même et pas de l'interface.
Plus exactement c'est l'API Firewall:getPortForwarding qui retourne une erreur dans votre cas.
Pour en savoir plus il faudrait regarder les logs, il y a forcément un message d'erreur doit apparaitre dans la console. Et encore mieux, activer les logs en niveau 2 (onglet "Actions"), et regarder le retour de la Livebox sur l'appel à Firewall:getPortForwarding.
Sinon si vous avez l'outil sysbus installé essayez tout simplement
`sysbus Firewall:getPortForwarding`
Aussi pourriez vous en dire plus sur le modèle de Livebox ? J'imagine que depuis le temps vous avez du essayer de la redémarrer n'est ce pas et cela n'a rien changé ?

**Comment by aldoushx** [comment]
Je suis sur la Livebox 4. 
Effectivement les redémarrage et restaurations ne marchent pas. Seule la désactivation de la sauvegarde cloud puis restauration marcheraient, mais ça me ferait perdre toutes mes règles et ip fixes donc j'attendais avec impatience la maJ du monitor !

J'ai installé sysbus, et effectivement quand je lance la requête ci-dessus, ça me retourne une ligne d'erreur en tête : "erreur: <class 'json.decoder.JSONDecodeError'>", puis "mauvais json:" et quand même la liste de mes redirections (ça doit être le contenu du json erroné, l'erreur doit figurer au milieu...)

**Comment by p-dor** [comment]
Mais justement il me faudrait l'intégralité de la réponse JSON de la requête pour en savoir plus sur ce qui ne va pas chez vous, pourriez vous la copier ici ? L'idéal serait d'activer les logs niveau 2 (soit dans sysbus soit dans LiveboxMonitor) et récupérer la réponse totale qui effectivement doit contenir les détails de l'erreur.

**Comment by aldoushx** [comment]
Je ne suis pas très friand d'exposer mes ports en public, je peux vous envoyer un .txt par un autre moyen ?

En effet, j'ai une tabulation qui apparait dans un nom de règle, quelques titres de règles remplis en aveugle qui sont possiblement trop longs, 2 règles avec le même nom et aussi 2 règles qui pointent vers le même port externe... c'est pas joli !

**Comment by p-dor** [comment]
Je comprends bien sûr. Vous pouvez m'envoyer ça sur mon email dorpierre@orange.fr et vous pouvez remplacer toutes les IPs et ports par des XXX cela n'aura aucune importance.
Pour les règles mon intuition semble se confirmer pour le coup... Et 2 règles avec le même nom en principe c'est totalement impossible, en tout cas sur la Livebox 5 si on essai de créer une règle avec le même nom qu'une autre celle ci est écrasée.
Si vous avez sysbus installé je vous conseille d'essayer d'effacer "manuellement" les règles avec un nom suspect avec la commande :
`sysbus Firewall:deletePortForwarding id='NOM_DE_LA_REGLE' destinationIPAddress='IP_DE_DESTINATION' origin='webui'`

Si cela ne fonctionne pas en entrant le nom de règle (paramètre id), essayez en précisant uniquement l'adresse IP de destination et l'origine ce qui aura pour effet de supprimer toutes les règles pointant sur cette adresse IP.
Et en dernier recours vous pouvez essayer avec uniquement le paramètre origin ce qui aura pour effet de supprimer toutes les règles mais au moins vous repartez sur une base saine.
Envoyez moi d'abord la réponse avec l'erreur si vous préférez confirmer d'abord que l'erreur vient bien de là...

**Comment by aldoushx** [comment]
C'est envoyé ! J'essaye via sysbus, les règles suspectes ne sont plus utilisées...

**Comment by aldoushx** [comment]
Test réalisé, toutes les règles remontent bien, y compris les upnp non visibles dans l'interface d'admin. 
Voilà les opérations testées : 

- Export des règles
- Modification d'une règle existante
- Désactivation d'une règle
- Suppression d'une règle

=> Tout est OK !

**Comment by p-dor** [comment]
Version 1.2 publiée avec l'amélioration, je ferme le ticket.
