### ISSUE TITLE
Config.txt not exist

### ISSUE THREAD

**Issue by drawkend** [p-dor/LiveboxMonitor#33]

**Comment by p-dor** [comment]
Please give further details. What happens, what do you see, any logs in the console?, etc...

**Comment by roumano** [comment]
From my linux machine, i got this error ( i think its related) :
```
~/git/LiveboxMonitor$ python3 LiveboxMonitor.py
Traceback (most recent call last):
  File "/home/ciuga/git/LiveboxMonitor/LiveboxMonitor.py", line 335, in <module>
    if LmConf.load():
  File "/home/ciuga/git/LiveboxMonitor/src/LmConfig.py", line 417, in load
    with open(aConfigFilePath) as aConfigFile:
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: './Config.txt'
```

**Comment by p-dor** [comment]
Oops, was due to an unfortunate commit (some lines were commented for debug purpose).
Pull again and it should be fine.
Thanks for the notification.

**Comment by roumano** [comment]
yes perfect, its working as expected
