### ISSUE TITLE
IP Address - Order by Numerical Order

### ISSUE THREAD

**Issue by saner-demirkol** [p-dor/LiveboxMonitor#35]
Bonjour,
Tout d'abord un GRAND peric pour cette outil.

Je voudrais juste demander s'il sera possible de configurer "Order By IP Address" en numérique, au lieu de chars
Actuellement il est 1x.0 - 10x - 11 - 12 etc...

![image](https://user-images.githubusercontent.com/129766734/229539034-e0bfc334-6e24-4add-be60-f3c0a6ea78f9.png)
Au lieu de ça, x.10 - 11 -12 ... sera plus logique visuellement
Merci d'avance

**Comment by p-dor** [comment]
Bonjour, mais oui et c'est une suggestion très valide !
En plus c'est très simple à réaliser...
Merci pour votre commentaire.

**Comment by p-dor** [comment]
Bonjour c'est maintenant fixé dans le repo (si vous lancez le programme directement depuis les sources) pour toutes les listes affichant des IPv4, et ce sera donc disponible aussi dans la prochaine release.

**Comment by p-dor** [comment]
La release v1.1 est maintenant publiée.
