### ISSUE TITLE
Changer l'ordre des onglets Repeteurs

### ISSUE THREAD

**Issue by saner-demirkol** [p-dor/LiveboxMonitor#36]
Bonjour,

Je voudrais vous demander comment on peut modifier l'ordre de visualisation des onglets "Repeteurs"
Par example dans mon cas, 

- Repeteur 1 -  MAC 0C:73:29:7F:10:XX - IP 192.168.1.5
- Repeteur 2 - MAC 0C:73:29:7F:2A:XX - IP 192.168.1.6

Je voudrais bien le montrer dans cette ordre, mais "drag" des onglets ne marche pas, et je n'ai pas trouvé une config visible dans config.txt 

![image](https://user-images.githubusercontent.com/129766734/229621555-6276a706-d290-4a6f-b7e4-592740e324c0.png)

En vous remerciant d'avance

**Comment by p-dor** [comment]
Bonjour, non il n'y a pas de possibilité de contrôler cet ordre, il est juste dépendant de l'ordre avec lequel la Livebox donne sa liste d'appareils détectés.
Il est très simple d'activer le drag&drop sur les tabs, mais cela perturbe le fonctionnement du programme qui est basé sur les index de ces tabs et le fait que les répéteurs soient bien listés à la fin... Est-ce vraiment si important ?

**Comment by saner-demirkol** [comment]
Bien-sûr que ce n'est si important, c'est juste un un détail, je suis d'accord. 
Je suis peut-être un peu manique :)

**Comment by p-dor** [comment]
Bonjour, comme ce n'était finalement pas très compliqué je viens de pousser sur le repo une évolution permettant de bouger n'importe quel onglet, y compris ceux des répéteurs, n'importe où et de retrouver ce même ordre lors du lancement (l'ordre est sauvé dans la configuration).
Ce sera dans la release qui arrive maintenant très très bientôt.

**Comment by p-dor** [comment]
La release v1.1 est maintenant publiée.
