### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by solsticedhiver** [p-dor/LiveboxMonitor#38]
J'essaye de lancer la version git 3e85e8b5cb833f316b6d39a1f7a82ae11cee3752 et j'obtiens cette erreur sur ubuntu 22.04.2 (paquet python installé avec apt pas pip)

```
Traceback (most recent call last):
  File "/home/stephane/Téléchargements/LiveboxMonitor/LiveboxMonitor.py", line 370, in <module>
    locale.setlocale(locale.LC_ALL, LmConf.Language.lower() + '_' + LmConf.Language.upper())
  File "/usr/lib/python3.10/locale.py", line 620, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

Application will now quit.
```

A première vue, je suis surpris de voir l'utilisation de LC_ALL pour changer la locale c'est pas LANG qu'on utilise d'habitude ?? PArce que moi LC_ALL est vide.

```
$ locale
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

J'ai essayé en supprimant la ligne en question (367?) et ça marche nickel. je l'ai même en français...

**Comment by p-dor** [comment]
Salut,

Non c'est bien LC_ALL, en tout cas si on suit la documentation, par exemple :
https://docs.python.org/3/library/locale.html
https://phrase.com/blog/posts/beginners-guide-to-locale-in-python/

En fait cette ligne est là surtout pour localiser les graphes dans l'onglet "Graphe" (pour les dates en abscisse), c'est l'utilité principale car le reste du programme est localisé d'une manière propriétaire.

Cela fonctionne bien chez moi sur Windows et Mac, et comme le dit la doc cet appel peut être capricieux en fonction du système et de son ancienneté. Je vais donc le protéger par un exception handler...

Merci pour l'avoir signalé.

**Comment by solsticedhiver** [comment]
A noter que j'ai eu un crash complet de gnome shell quand je suis arrivé sur les graphes, je sais plus où dans l'interface. Aucune idée si c'est mon OS, mon desktop, ma machin ou LiveboxMonitor.

**Comment by p-dor** [comment]
Reproductible le crash ?
Les graphes sont basés sur pyqtgraph, si c'est ce package qui provoque le problème il suffit d'essayer avec un petit programme qui l'utilise, comme par exemple dans ce tuto :
https://www.pythonguis.com/tutorials/plotting-pyqtgraph/

Merci pour l'information pour la locale, je vais rajouter l'encoding du coup.

**Comment by solsticedhiver** [comment]
je suis plus sur la machine en question et pas de livebox sous la main. demain

**Comment by p-dor** [comment]
Je vais garder le ticket ouvert un petit peu si jamais vous trouvez de nouveaux indices, mais en l'état difficile d'investiguer quoi que ce soit hélas...

**Comment by p-dor** [comment]
Je ferme le ticket pour le problème initial (local.error) qui est fixé dans la release 1.1. Pour le problème de crash de gnome-shell il faudra passer par un autre ticket si d'autres éléments peuvent être apportée pour identifier un éventuel problème à régler.
