### ISSUE TITLE
Wrong or inexistant MacAddrTable.txt file

### ISSUE THREAD

**Issue by nscheffer** [p-dor/LiveboxMonitor#4]
Bonjour Pierre,

Je viens de recevoir le mail pour la version 0.9.7 avec le support de multiple Livebox (merci d'avance !) mais pas de version Mac en download, un oubli ?

De plus il y a seulement une version Intel, une version universelle en vue (ou Apple Sillicon) ?

Dernier point quelle est la difference entre la version normale et la version Console ?

**Comment by nscheffer** [comment]
J'ai pas assez attendu je viens de voir la version Mac, je file...

**Comment by nscheffer** [comment]
C'est top !
Par contre à chaque changement de profil j'ai le message dans un dialogue à part "Wrong or inexistant MacAddrTable.txt file." est ce normal ?
Je ne peux que faire Ok sur le dialogue !

![Capture d’écran 2023-01-22 à 19 11 12](https://user-images.githubusercontent.com/207886/213932632-ed4f0a8d-d159-4661-9a2a-2ec988bbdf4c.png)

**Comment by p-dor** [comment]
Bonsoir ! Oui il y a toujours un petit délai entre la version Windows et la version Mac que je construis séparément. Comme je n'ai qu'un Mac intel je ne me suis pas encore penché sur un build Sillicon en cross-compilation, ce n'est pas très simple à faire.

Sinon la différence entre la version normale et la console c'est que... la version console affiche une fenêtre de console en plus du programme pour pouvoir suivre les logs. C'est utile pour débugger ou comprendre ce qui se passe.

Et pour le dialogue "Wrong or inexistant MacAddrTable.txt file" c'est normal, il va afficher cela tant qu'un fichier n'a pas été créé et un bon moyen de le faire c'est d'assigner un nom à n'importe quel appareil et c'est parti. Mais c'est vrai que c'est un peu gênant ce dialogue, je crois que je vais plutôt opter pour créer le fichier vide directement s'il n'existe pas...

**Comment by bereldhuin** [comment]
+1 pour la création d'un fichier vide sans avoir de message ;-)

**Comment by p-dor** [comment]
C'est maintenant réglé dans les sources, et ce sera disponible dans la prochaine release.

**Comment by p-dor** [comment]
Intégré dans la v1.0. Je ferme maintenant le ticket.
