### ISSUE TITLE
Ajouter un Shebang et mettre le fichier LiveboxMonitor.py en exécution

### ISSUE THREAD

**Issue by KanaChan06** [p-dor/LiveboxMonitor#47]
Salut !
Ce serait bien que vous rajoutiez le Shebang de python3  au début du fichier LiveboxMonitor.py et de le rendre exécutable :
* mettre  #!/usr/bin/env python3
* faire un chmod +x LiveboxMonitor.py

Voilà, sinon comme d'habitude, superbe application !
Merci.

**Comment by p-dor** [comment]
Ok ! Je fais ça dès que possible. Mon fidèle PC est mort aujourd'hui, il va falloir attendre un certain moment avant que je puisse reprendre... :-(

**Comment by p-dor** [comment]
Merci à @LiteApplication pour la contribution !
Mon nouveau PC étant maintenant à peu près opérationnel je vais pouvoir reprendre le dev de temps en temps...
