### ISSUE TITLE
Migrer vers une Web App (Flask ?)

### ISSUE THREAD

**Issue by bFernandKind** [p-dor/LiveboxMonitor#48]
L'application est bien plus agréable que la web app native de la livebox, plus rapide, plus claire, plus ergonomique.

Son seul défaut amha est qu'il s'agit d'une application et non pas d'une web app ! 

S'il était possible de migrer de Qt vers Flask elle pourrait être hébergée en tant que web app alternative pour être consultée facilement sans devoir activer le contrôle à distance.

**Comment by p-dor** [comment]
Bonsoir @bFernandKind, vous n'êtes pas le premier à faire cette remarque, mais c'est le choix de départ qui a été fait pour simplifier le déploiement et utilisation de l'application. Le code de la UI est totalement lié au code de l'application elle même et migrer à une approche client/serveur représenterait un énorme travail que je ne peux pas me permettre. Si quelqu'un veut se lancer dans l'aventure je suis cependant disposé à donner tout le support possible.
