### ISSUE TITLE
Net graph + historique DL / UP kb/s

### ISSUE THREAD

**Issue by jo13310** [p-dor/LiveboxMonitor#5]
Quel travail monstre, bravo.

Je n'ai pas réussi pour autant à trouver comment modifier de moi même l'application afin d'apporter un graphique type Net graph ainsi qu'une sauvegarde dans un csv des données d'upload et de download afin de monitorer mes appareils. 

Je pense que cela serait d'une grand aide car j'avoue que, la base de ma recherche m'ayant fait trouvé votre outil était de pouvoir monitor mon réseau afin de trouver une utilisation anormale d'un appareil ! :)

**Comment by p-dor** [comment]
Bonsoir jo13310 merci pour le compliment ! Je m'amuse bien avec cette application :-)

Que voulez vous dire par "je n'ai pas réussi à trouver comment modifier de moi même l'application" ? Avez vous un problème avec GitHub pour soumettre des Pull requests ou c'est le code lui même qui vous semble obscur ? En fonction de ce que vous voulez faire je peux essayer de vous guider. Effectivement je n'ai écrit aucune documentation sur le code lui même, ce serait un travail au delà de ce que peut me permettre mon pauvre temps libre...

Si ce que vous recherchez est de générer des alertes proactives (par mail ? par SMS ?) lorsque quelque chose que vous jugez anormal se produit (un appareil inconnu se connecte ? un traffic up/down au delà d'un seuil sur une durée donnée ?) c'est peut être plus simple à faire que d'afficher un graphe dynamique ou d'exporter dans un fichier CVS qui sera analysé offline.

**Comment by jo13310** [comment]
J'ai voulu essayé d'implémenter moi-même la modification mais je ne suis pas assez bon.

Mon souhait est d'avoir une page stats : 

- Un graphique UP/DOWN de 0 kb/s à Max kb/s en temps réel, avec tout les devices affichables ou non et des couleurs différentes
- et d'avoir la possibilité d'avoir un logger sur x minutes, avec a la clé un fichier CSV qui permet de voir le up/down a chaque secondes, ce qui permet de debugg un appareil qui par exemple chinois, envoi x mb de données dans l'heure alors que ce n'est qu'un capteur de température .. :)

**Comment by p-dor** [comment]
Je vais essayer de voir pour un export CSV déjà, pas très compliqué, et des logiciels externes permettront d'afficher ça sous forme de graphe aussi de toute façon.

**Comment by p-dor** [comment]
Prochaine priorité du projet.
Je pense partir sur PyQtGraph pour ça, si quelqu'un a de meilleures suggestions...

**Comment by p-dor** [comment]
Bonjour, je viens de publier sur le repo le support d'un nouveau tab "Graphe" qui permet de visualiser toutes les statistiques, au niveau d'une interface ou d'un appareil. Ces statistiques sont en fait stockées par la Livebox sur une fenêtre de plusieurs jours et avec une fréquence d'échantillonnages de 30 secondes.
Le graphe se met à jour aussi en temps réel pour les interfaces / appareils sélectionnés.
Et le support d'un export CSV est aussi fourni.

![LiveboxMonitor Graph](https://user-images.githubusercontent.com/68299472/235306837-478c5742-33cb-46ac-b93b-e0e1cb842cd8.png)

Merci de me faire un retour si quelque chose ne fonctionne pas bien, je vais probablement publier la nouvelle release dans les jours qui viennent.

**Comment by p-dor** [comment]
La release v1.1 contenant cette évolution est maintenant publiée.
