### ISSUE TITLE
[README] [LINUX] Explicit dependencies of the project in the Readme

### ISSUE THREAD

**Issue by floviolleau** [p-dor/LiveboxMonitor#51]
Hi,

I had troubles recently to install this application.

I used a virtualenv like explained here: https://github.com/p-dor/LiveboxMonitor/issues/7#issuecomment-1410668659

What was missing now since 1.0 version are:
- apt install qt6-base-dev
- apt install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev

Without that, I had  the following error:
```bash
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland, linuxfb, xcb, minimalegl, wayland-egl, vnc, vkkhrdisplay, eglfs, minimal, offscreen.

[1]    410356 IOT instruction (core dumped)  python3 LiveboxMonitor.py
```

Can you please add those details in the Readme?
Thanks

**Comment by p-dor** [comment]
Done, and thank you for your contribution!
