### ISSUE TITLE
Attribution des couleurs du SignalRxPower

### ISSUE THREAD

**Issue by aerogus** [p-dor/LiveboxMonitor#54]
Je ne comprends pas bien les conditions qui attribuent les status et les couleurs en fonction de la puissance de réception .

https://github.com/p-dor/LiveboxMonitor/blob/22fb2408e5bdc9bbefb2c692b86e74d78a5e955d/src/LmInfoTab.py#L1136C6-L1136C6

```
				if (v < -27.0) or (v > -8.0):
					aQual = LmTools.ValQual.Error
				elif (v < -22.0) or (v > -2.0):
					aQual = LmTools.ValQual.Warn
				else:
					aQual = LmTools.ValQual.Good
```

devrait être plutôt ?

```
				if (v < -27.0) or (v > -2.0):
					aQual = LmTools.ValQual.Error
				elif (v < -22.0) or (v > -8.0):
					aQual = LmTools.ValQual.Warn
				else:
					aQual = LmTools.ValQual.Good
```

ERR
-2 dBm
WARN
-8 dBm
GOOD
-22 dBm
WARN
-27 dBm
ERR

**Comment by p-dor** [comment]
Bonjour, vous avez totalement raison c'était une erreur.
Je viens de pousser la correction, merci pour l'avoir signalé !
