### ISSUE TITLE
Obtenir de l'etat du CPU

### ISSUE THREAD

**Issue by imclint21** [p-dor/LiveboxMonitor#55]
Bonjour,

Ya til moyens de recuperer l'utilisation du processeur ou ce genre d'inforamtions @p-dor ?

Cordialement

**Comment by p-dor** [comment]
Bonsoir @imclint21, il y a bien un module Livebox appelé 'CPUStats' qui j'en suis sûr doit fournir ce type d'information mais pour une raison qui n'appartient qu'à Orange l'accès n'est pas permis pour le user 'admin' que nous utilisons tous...
'access denied' est la seule réponse possible et c'est bien dommage, surtout qu'on peut se demander la raison qui justifie d'avoir bloqué ce type d'information...

Sinon il reste toujours possible de choper la liste des processes qui tournent. Pour cela direction le fichier _PROCESSES_.txt qui est généré si vous cliquez sur le bouton "Générer Documentation APIs"  dans l'onglet Action.

**Comment by imclint21** [comment]
Ah oui totalement idiot, nous avons des gros soucis de lenteurs donc nous pensons naturellement à un reach de la limite du CPU mais impossible de le confirmer.
