### ISSUE TITLE
Undefined symbol? on venv

### ISSUE THREAD

**Issue by kuentinos** [p-dor/LiveboxMonitor#56]
Traceback (most recent call last):
  File "/git/LiveboxMonitor/LiveboxMonitor.py", line 10, in <module>
    from PyQt6 import QtCore, QtGui, QtWidgets
ImportError: /git/LiveboxMonitor/.venv/lib/python3.11/site-packages/PyQt6/QtCore.abi3.so: undefined symbol: _ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate, version Qt_6_PRIVATE_API

**Comment by kuentinos** [comment]
On commit 4ca4ec8

**Comment by p-dor** [comment]
Hello, sorry I don't use venv and cannot really help but it looks like an installation issue on your side.
This is NOT linked to the program: your configuration doesn't allow to import PyQt6 QtCore.

You can check those pages if they can help:
[https://stackoverflow.com/questions/74122037/importerror-home-me-anaconda3-envs-sniptest-lib-python3-9-site-packages-pyqt5?rq=2](url)
[https://stackoverflow.com/questions/77161734/pyqt5-qtcore-abi3-so-undefined-symbol-zdapvm-version-qt-5-on-python3-8-ubun](url)
