### ISSUE TITLE
Error: No module named 'universaldetector'

### ISSUE THREAD

**Issue by KevinGIRAULT** [p-dor/LiveboxMonitor#57]
Après avoir lancé le script, une fois tapé l'URL et appuyé sur entrée, j'ai le message suivant dans le terminal :

```
name@pc:~/LiveboxMonitor$ python3 LiveboxMonitor.py 
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (2.1.1) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Error: No module named 'universaldetector'
Error: No module named 'universaldetector'
name@pc:~/LiveboxMonitor$ 
```
J'ai installé les paquets suivants via pipx :
- chardet
- cchardet
- urllib3
- dirsearch

Mais ça ne règle pas la situation, le même message d'erreur s'affiche.

**Comment by p-dor** [comment]
Bonsoir, pouvez vous donner un peu plus d'information sur votre environnement ? Version de Python ? Linux/Windows/Mac ? Virtualenv ?
Est-ce que ce thread aide ?
https://github.com/omz/Pythonista-Issues/issues/554
