### ISSUE TITLE
MacAddrTable.txt non créé

### ISSUE THREAD

**Issue by nicolab28** [p-dor/LiveboxMonitor#62]
J'utilise la version v1.4 en exe sous windows 11 et une livebox 6 en fibre
Le fichier MacAddrTable.txt n'est pas créer dans le dossier %APPDATA%\LiveboxMonitor
J'ai bien de dossier cache et le config.txt
Du coup impossible d'assigner les noms.
Si je crée un fichier MacAddrTable.txt vide, au lancement j'ai le message "Wong MacAddrTable.txt file format, cannot use." Si je lui mets des {} dedans pour créer un json vide, rien ne se passe.
Sinon beau travail!

**Comment by nicolab28** [comment]
Ok, j'ai compris mon erreur!

Je suis en mode sombre, et j'avais déjà nomé quasi tous mes devices.
Du coup quand j'ai vu qu'ils étaient tous inconnu en rouge, j'ai cliqué sur Asssigner un Nom.
Mais , en mode sombre, la case à cocher Nom Local est remplie en bleu, et la ligne de texte est invisible. J'ai bien le nom Livebox de rempli, et j'avais bon cliquer sur OK, rien ne se passait... (logique, avec un peu de recul)

Pourquoi ne pas utiliser le nom Livebox comme nom local, s'il est défini? Qu'elle est l'interet du nom Local?

![Sans titre-1](https://github.com/p-dor/LiveboxMonitor/assets/56133081/1cf8d322-35fd-430f-bfd3-6cd2a72a4b5a)

**Comment by p-dor** [comment]
Pour cela je vous renvoie à la documentation que je vous recommande de parcourir tout de même un petit peu ;-)
Notamment ce [petit paragraphe](https://github.com/p-dor/LiveboxMonitor?tab=readme-ov-file#le-fichier-macaddrtabletxt).
L'intérêt principal c'est de pouvoir contrôler en un coup d'oeil si tous les appareils que vous voyez sont bien connus par vous ou s'il y a des intrus. Mais ce n'est pas le seul, bien souvent la LB bug et oublie des noms, sans compter le fait que si un appareil ne se connecte pas au bout d'un mois il est automatiquement oublié.
