### ISSUE TITLE
Installation avec pipx

### ISSUE THREAD

**Issue by LaurentBonnaud** [p-dor/LiveboxMonitor#63]
Bonjour,
serait-il possible de rendre LiveboxMonitor installable avec `pipx` ?
L'installation serait alors extrêmement simple avec cette unique commande:
`pipx install LiveboxMonitor`
Cordialement.

**Comment by p-dor** [comment]
Bonjour, je ne connaissais pas, mais je peux commencer déjà pas publier l'application dans `PyPI`.
Je vais voir ce qu'il y a à faire en plus pour `pipx`, ça ne doit pas être bien sorcier.
À bientôt.

**Comment by p-dor** [comment]
Bonsoir,
Une version 1.4.8 intermédiaire (en attendant la 1.5) est maintenant disponible sur `PyPI` : https://pypi.org/project/LiveboxMonitor/

`pip install LiveboxMonitor` fonctionne et j'imagine qu'un `pipx install LiveboxMonitor` devrait aussi.

@LaurentBonnaud  pourriez vous confirmer?

**Comment by LaurentBonnaud** [comment]
Bonjour,
je confirme que LiveboxMonitor s'installe maintenant très facilement sous Linux avevc pipx.
Merci beaucoup !
```
$ pipx list
[...]
   package liveboxmonitor 1.4.8, installed using Python 3.12.3
    - LiveboxMonitor

```
