### ISSUE TITLE
Impossible d'ajouter une entrée DHCP

### ISSUE THREAD

**Issue by bedouinvert** [p-dor/LiveboxMonitor#64]
Une erreur survient lors de l'ajout d'une réservation DHCP.
![Screenshot_20240528-182413](https://github.com/p-dor/LiveboxMonitor/assets/3938833/a55cb544-c15f-4df8-b9f8-8790669d3cb4)

**Comment by bedouinvert** [comment]
Finalement, il n'y a plus d'erreur après un arrêt/marche du DHCP de la livebox.

**Comment by p-dor** [comment]
J'étais justement en train de regarder et c'était très étrange : comme si la Livebox ne retournait pas une IP pour identifier le serveur DHCP. Vous auriez pu le vérifier en regardant dans les infos DHCP ce qui était affiché en face de "DHCPv4 Gateway" mais trop tard :-)
Je vais tout de même blinder le programme du coup pour faire face à cette situation sans planter car pour le moment il assume sans tester qu'il s'agit d'une adresse IPv4.
Merci de l'avoir signalé.
