### ISSUE TITLE
requirements.txt on Linux

### ISSUE THREAD

**Issue by ctotof38** [p-dor/LiveboxMonitor#7]
Bonjour,

le fichier requirements.txt contient webbrowser. Sur Linux, ce paquet n'existe pas, il est déjà inclus dans la distribution Python3
Cela génère l'erreur : 
```
ERROR: Could not find a version that satisfies the requirement webbrowser (from versions: none)
ERROR: No matching distribution found for webbrowser
```

**Comment by p-dor** [comment]
Et je crois que c'est pareil pour les autres distributions... Dans le doute je l'avais rajouté mais votre commentaire confirme que ce n'est pas nécessaire, bien au contraire. Merci !

**Comment by bereldhuin** [comment]
Excellent outil, enfin une interface fluide et rapide pour la LiveBox 5 ;-)

Le logiciel fonctionne parfaitement sous Linux (Ubuntu 22.04), en supprimant webbrowser dans le fichier requirements.txt.
Il faut juste valider le message Wrong MacAddrTable.txt et cliquer sur "Attendre" pour que la table se charge. 

Pour ceux qui veulent également le lancer sous Linux, il faut lancer les commandes suivantes (peut-être pourriez-vous l'ajouter dans la doc ;-) ) : 
```
git clone https://github.com/p-dor/LiveboxMonitor.git
cd LiveboxMonitor
pip install -r requirements.txt
python3 LiveboxMonitor.py
```

**Comment by floviolleau** [comment]
Bonjour,

Un grand merci à @p-dor pour ce superbe logiciel !

Avec un virtualenv, c'est encore mieux ! Ça évite d'installer les dépendances sur toute la machine

```bash
git clone https://github.com/p-dor/LiveboxMonitor.git
cd LiveboxMonitor
virtualenv -p python3 .venv
source .venv/bin/activate
pip install -r requirements.txt
python3 LiveboxMonitor.py
```

Pour relancer si le terminal a été quitté :

```bash
cd LiveboxMonitor
source .venv/bin/activate
python3 LiveboxMonitor.py
```

**Comment by floviolleau** [comment]
On peut même directement : `.venv/bin/python LiveboxMonitor.py` sans avoir besoin de source activate avant

**Comment by p-dor** [comment]
v1.0 publiée et documentation à jour. Je ferme maintenant le ticket.
