### ISSUE TITLE
Bloquer / débloquer un appareil depuis LiveboxMonitor ou API?

### ISSUE THREAD

**Issue by josephernest** [p-dor/LiveboxMonitor#72]
Bonjour,

Bravo pour ce super projet!

* 1\) Est-ce possible de bloquer/débloquer l'accès internet d'un périphérique donné depuis LiveboxMonitor? 

    Ou, si pas encore disponible, y a-t-il une API Livebox pour cela? (dans ce cas, je pourrais essayer de rajouter cette fonctionnalité...)

    Le but serait de pouvoir faire, depuis LiveboxMonitor, `Paramétrer son accès à internet` > `Autoriser en permanence` / `Bloquer en permanence` :

    ![image](https://github.com/user-attachments/assets/3d256b70-1b2c-42c5-a11b-4ef8b05d38ac)

* 2\) Cerise sur le gâteau : peut-on faire cela pour l'appareil "décodeur TV"? Etrangement `Autoriser en permanence` / `Bloquer en permanence` n'est pas disponible pour le décodeur TV depuis l'interface classique 192.168.1.1.

Merci d'avance et bravo encore!

**Comment by p-dor** [comment]
Bonjour, des boutons "Bloquer" / "Débloquer" sont disponibles via l'onglet "Infos Appareil" qui ont le même effet que l'option "bloquer/autoriser en permanence" sur l'interface web. Cela marche plus ou moins bien en fonction des appareils et de leur interface. Dans LiveboxMonitor vous pouvez essayer aussi sur le décodeur TV.

Merci pour vos commentaires encourageants !

**Comment by josephernest** [comment]
Merci beaucoup pour la réponse @p-dor!

> des boutons "Bloquer" / "Débloquer" sont disponibles via l'onglet "Infos Appareil" qui ont le même effet que l'option "bloquer/autoriser en permanence" sur l'interface web.

Ca marche en effet

> Dans LiveboxMonitor vous pouvez essayer aussi sur le décodeur TV

Hélas ça ne fonctionne pas. Même quand l'état est sur "blocked", le flux vidéo continue de passer. Je crois avoir lu un jour que le flux vidéo passe par un autre sous-réseau local, non administrable par l'admin Livebox, est-ce le cas?

Une idée comment je pourrais bloquer le décodeur TV ponctuellement (sans toutefois bloquer le Wifi) ?  
(Pour limiter les enfants ce serait très pratique ;))

**Comment by p-dor** [comment]
Si le blocage "normal" ou de l'adresse MAC du décodeur ne fonctionne pas une idée serait peut être de faire un petit script qui éteint le décodeur automatiquement s'il est allumé, que vous pourriez faire tourner régulièrement. Je n'ai pas mieux :-)

Pour que cela fonctionne une faut s'assurer que l'IP du décodeur soit fixe via le DHCP.
Si par exemple l'IP est 192.168.1.10 avec cette URL vous pouvez savoir si le décodeur est allumé : http://192.168.1.10:8080/remoteControl/cmd?operation=10
Si le champs "activeStandbyState" est à 0 cela signifie que le décodeur est allumé (il est à 1 si en standby).

Ensuite avec l'URL :
http://192.168.1.10:8080/remoteControl/cmd?operation=01&key=116&mode=0
en principe vous éteignez le décodeur.

**Comment by josephernest** [comment]
Intéressant! Je vais creuser cela!

J'en profite pour deux dernières questions:

* peut-on block/unblock un device directement avec une URL du genre:

      http://192.168.1.10:8080/remoteControl/cmd?operation=xxx&key=yyy&mode=zzz&device=iPhone-de-ABC&action=block
      http://192.168.1.10:8080/remoteControl/cmd?operation=xxx&key=yyy&mode=zzz&device=iPhone-de-ABC&action=unblock

    ?

* si jamais vous avez l'occasion de tester le blocage du décodeur TV par la méthode "blocage MAC" (cf https://github.com/p-dor/LiveboxMonitor/issues/34#issuecomment-2380840267), ça m'intéresse ;)

**Comment by p-dor** [comment]
Non ces URLs ne fonctionnent que pour le décodeur TV.
Si vous voulez bloquer/débloquer par un script il faut appeler directement les APIs de la Livebox.
Si vous connaissez Python vous pouvez reprendre le code des fonctions blockDeviceButtonClick() et unblockDeviceButtonClick() du fichier LmDeviceInfoTab.py, en utilisant une session ouverte par LmSession.py.  La clef est l'adresse MAC de l'appareil.

**Comment by josephernest** [comment]
Merci @p-dor, je vais suivre ces conseils!
