### ISSUE TITLE
API Livebox pour faire visiter une URL par la Livebox à chaque redémarrage

### ISSUE THREAD

**Issue by josephernest** [p-dor/LiveboxMonitor#73]
Re-bonjour,

@p-dor toi qui a fait beaucoup de reverse engineering, peut-être as-tu trouvé cela: est-ce possible, via l'API Livebox, de fixer une URL custom qui sera visitée par la Livebox à chaque démarrage/redémarrage de la box?

Ca me permettrait de faire une sorte de DynDNS maison, avec mon propre serveur, sans passer par un service externe pour cela.

Si chaque fois que la box redémarre, elle envoie une requête à https://monserveur.fr/hidden1234/update, mon serveur pourrait récupérer l'IP d'où vient la requête et modifier le DNS d'un de mes noms de domaine pour pointer vers cette IP. Un DynDNS auto-hébergé en quelque sorte.

Mais pour cela, il faut pouvoir faire en sorte que la Livebox "ping" cette URL à chaque changement d'IP et/ou redémarrage.

Merci d'avance pour toute idée!

**Comment by p-dor** [comment]
Bonjour @josephernest, non désolé de ce que j'ai pu voir jusqu'à présent ce genre de choses me semble totalement impossible.
Le package DynDNS de la box ne permet pas de rajouter d'autres services que ceux prédéfinis et gérés automatiquement ( "dyndns", "No-IP", "ChangeIP", "OVH-dynhost", "GnuDIP").
