### ISSUE TITLE
Stats Livebox : erreur ?!

### ISSUE THREAD

**Issue by g4h4** [p-dor/LiveboxMonitor#75]
Bonjour !

Onglet: "Stats/Livebox" (Livebox 5)

D'ou viennent ces infos ?  (87.8 c'est Rx et 33.2 c'est Tx)
![{24E39225-DA08-4730-8CAF-97219235A630}](https://github.com/user-attachments/assets/b7de09e6-78b0-454a-b668-d981e40d1a55)

Sur l'interface classique je vois 4 Go en reçu (Rx) et non 87.8 Go:

![{FFE9A1AB-D87A-4F57-A4C4-25C98F5B7488}](https://github.com/user-attachments/assets/1543be92-bc2b-4a59-bd89-dd8839c2cbe2)
![{6DA2A025-00F2-48D7-9912-AB7CD051CCE9}](https://github.com/user-attachments/assets/4662711c-6929-4707-b3dd-6eb5e81adeea)

Seconde question, dans l'interface principale je vois :

![{8060093E-8AD4-4A1A-ADAE-E166AB0F7C07}](https://github.com/user-attachments/assets/99417027-123a-4508-92ed-e3cb8f8e9b98)

Ces statistiques sont depuis quand ? Journée / semaine / mois en cours ?

Merci.

**Comment by p-dor** [comment]
Bonjour !
Obtenir des statistiques fiables de la Livebox n'est pas chose aisée, car plusieurs services et événements différents donnent des compteurs par interface et/ou par appareil. Et pour corser le tout, tous ces services/événements donnent des compteur différents pour la même chose et il n'est pas facile non plus de comprendre pourquoi.
Pour votre première question j'ai choisi de prendre ces statistiques du module "HomeLan" de la Livebox, qui est aussi ce module qui permet d'afficher les courbes de traffic dans l'onglet "Graphe". La différence avec ce qu'affiche la page d'info de la webapp de la Livebox vient du fait que ce n'est pas du tout le même service qui est utilisé derrière... Mais j'ai préféré miser sur la cohérence et utiliser la même source pour cet écran et les courbes de trafic.
C'est aussi "HomeLan" qui est utilisé pour les statistiques par appareil (votre deuxième question) et en principe il s'agit de compteurs réinitialisés au démarrage de la Livebox. Donc il s'agit du trafic total depuis le dernier démarrage. Cependant ces compteurs sont circulaires, et repassent à zéro lorsqu'ils atteignent leur valeur maximum (que je n'ai pas essayé de déterminer).

Sachez aussi que pour certains appareils (notamment les appareils iOS) le trafic mesuré est bien plus important que ce qu'il est en réalité. Mais je n'ai pas réussi à comprendre pourquoi la Livebox pouvait se tromper à ce point... Il faut donc prendre ces statistiques avec des pincettes.

Notez que les tooltips sont là pour vous aider à répondre à ces questions ;-)
Il y en a aussi pour les titres de colonnes.
