### ISSUE TITLE
Contacts details wrong phone number

### ISSUE THREAD

**Issue by floviolleau** [p-dor/LiveboxMonitor#78]
Hi,

If I save several contacts with the same contact name of different phone number, when I reopen edit modal, it opens the first contact saved with this name.

It should opens the correct one.

Maybe, we can assign a unique id to each phone numbers?

Thanks

**Comment by p-dor** [comment]
Hi, this is because the search was by name first then by number.
I just pushed a fix to search by number first, could you please confirm this is fixing your issue?
